// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVUvkptucf1QFBYburuQSa4laY3G7DCHU',
    appId: '1:945038748268:web:1453c1cae18f372dbe8649',
    messagingSenderId: '945038748268',
    projectId: 'appdevproject-55ac8',
    authDomain: 'appdevproject-55ac8.firebaseapp.com',
    storageBucket: 'appdevproject-55ac8.firebasestorage.app',
    measurementId: 'G-5RCQTQ20P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4iinFhTY5a1MoOQPRI8txPrp01LMG_SQ',
    appId: '1:945038748268:android:0aca1daf0774cc31be8649',
    messagingSenderId: '945038748268',
    projectId: 'appdevproject-55ac8',
    storageBucket: 'appdevproject-55ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVJTTlS7WDY5_S3s6784eUu5i9Hz-bqCI',
    appId: '1:945038748268:ios:fe23678e3867f573be8649',
    messagingSenderId: '945038748268',
    projectId: 'appdevproject-55ac8',
    storageBucket: 'appdevproject-55ac8.firebasestorage.app',
    iosBundleId: 'com.example.appDevQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVJTTlS7WDY5_S3s6784eUu5i9Hz-bqCI',
    appId: '1:945038748268:ios:fe23678e3867f573be8649',
    messagingSenderId: '945038748268',
    projectId: 'appdevproject-55ac8',
    storageBucket: 'appdevproject-55ac8.firebasestorage.app',
    iosBundleId: 'com.example.appDevQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUvkptucf1QFBYburuQSa4laY3G7DCHU',
    appId: '1:945038748268:web:0cbb28947b154bc5be8649',
    messagingSenderId: '945038748268',
    projectId: 'appdevproject-55ac8',
    authDomain: 'appdevproject-55ac8.firebaseapp.com',
    storageBucket: 'appdevproject-55ac8.firebasestorage.app',
    measurementId: 'G-P72M4XHSYE',
  );
}
